# Generated by Django 4.1.7 on 2023-03-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('level', models.CharField(choices=[('0', 'Всеросс'), ('1', 'Первый уровень'), ('2', 'Второй уровень '), ('3', 'Третий уровень')], default='VOS', max_length=3)),
            ],
        ),
    ]
