# Generated by Django 4.1.7 on 2023-03-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0002_alter_olympiad_options_alter_olympiad_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='slug',
            field=models.SlugField(default='vos'),
        ),
    ]
