# Generated by Django 4.1.7 on 2023-03-24 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_period_options_period_unique period'),
        ('olympiads', '0005_exercisetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisetype',
            options={'ordering': ['type']},
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='type',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.CreateModel(
            name='OlympiadExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('contents', models.TextField()),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='olympiads.olympiad')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='core.period')),
            ],
        ),
    ]
