# Generated by Django 4.1.7 on 2023-03-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0007_olympiadexercise_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OlympiadExercise',
        ),
    ]
