# Generated by Django 4.1.7 on 2023-03-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0009_olympiadexercise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OlympiadExercise',
        ),
    ]
