# Generated by Django 4.1.7 on 2023-03-24 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_period_options_period_unique period'),
        ('olympiads', '0010_delete_olympiadexercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlympiadExercise',
            fields=[
                ('code', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('task_description', models.TextField()),
                ('contents', models.TextField()),
                ('slug', models.SlugField()),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='olympic_exercises', to='olympiads.olympiad')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='olympic_exercises', to='core.period')),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='olympic_exercises', to='olympiads.exercisetype')),
            ],
            options={
                'ordering': ['type', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='olympiadexercise',
            constraint=models.UniqueConstraint(fields=('type', 'code'), name='Unique task code'),
        ),
    ]
