# Generated by Django 4.1.7 on 2023-03-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0011_olympiadexercise_olympiadexercise_unique task code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
