# Generated by Django 4.1.7 on 2023-03-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0013_olympiad_period_alter_olympiad_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='level',
            field=models.CharField(choices=[('0', 'Всеросс'), ('1', 'Первый уровень'), ('2', 'Второй уровень '), ('3', 'Третий уровень')], default='VOS', max_length=3),
        ),
    ]
