# Generated by Django 4.1.7 on 2023-03-27 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_period_options_period_unique period'),
        ('olympiads', '0014_alter_olympiad_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='olympiads', to='olympiads.level'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='olympiads', to='core.period'),
        ),
    ]
