# Generated by Django 4.1.7 on 2023-03-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0016_tag_olympiad_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag']},
        ),
        migrations.RemoveField(
            model_name='olympiad',
            name='tags',
        ),
        migrations.AddField(
            model_name='olympiadexercise',
            name='tags',
            field=models.ManyToManyField(related_name='olympiads', to='olympiads.tag'),
        ),
    ]
