# Generated by Django 4.1.7 on 2023-03-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0017_alter_tag_options_remove_olympiad_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='olympiad',
            options={'ordering': ['-period', 'id']},
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='slug',
            field=models.SlugField(),
        ),
    ]
