# Generated by Django 4.1.7 on 2023-03-23 18:02

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveBigIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2000), core.models.max_year])),
            ],
        ),
    ]
