# Generated by Django 4.1.7 on 2023-03-23 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['year']},
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='end_years', to='core.year')),
                ('start_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start_years', to='core.year')),
            ],
        ),
    ]
