# Generated by Django 4.1.7 on 2023-03-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_year_options_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['start_year', 'end_year']},
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('start_year', 'end_year'), name='Unique period'),
        ),
    ]
