# Generated by Django 4.1.7 on 2023-03-27 20:40

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_period_options_period_unique period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.PositiveBigIntegerField(default=2023, unique=True, validators=[django.core.validators.MinValueValidator(2000), core.models.max_year]),
        ),
    ]
